export { OverviewStatsWidget } from '@/components/widgets/overview-stats-widget'
export { ProgressWidget } from '@/components/widgets/progress-widget'
export { InventoryWidget } from '@/components/widgets/inventory-widget'
export { ReportWidget } from '@/components/widgets/report-widget'
export { DailyReportWidget } from '@/components/widgets/daily-report-widget'
export { SecurityAlertsWidget } from '@/components/widgets/security-alerts-widget'
export { EntryExitWidget } from '@/components/widgets/entry-exit-widget'
export { ScheduleWidget } from '@/components/widgets/schedule-widget'
export { SafetyWidget } from '@/components/widgets/safety-widget'
export { FinancialWidget } from '@/components/widgets/financial-widget'
export { WidgetShell, WidgetGrid, WidgetGridItem } from '@/components/widgets/widget-shell'
