import type { AccountingDocument } from '@/lib/finance/expense-types'
import { formatRial } from '@/lib/finance/format-currency'

function escapeCsv(value: string | number | null | undefined): string {
  const s = value == null ? '' : String(value)
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`
  return s
}

/** Build CSV content for expense document list (UTF-8 BOM for Excel/Persian). */
export function buildExpenseCsv(rows: AccountingDocument[], locale: 'fa' | 'en' = 'fa'): string {
  const headers =
    locale === 'fa'
      ? [
          'شماره سند',
          'شماره فاکتور',
          'تأمین‌کننده',
          'تاریخ',
          'نوع هزینه',
          'مبلغ',
          'وضعیت',
          'شرح',
        ]
      : [
          'Document No',
          'Invoice No',
          'Supplier',
          'Date',
          'Cost Type',
          'Amount',
          'Status',
          'Description',
        ]

  const lines = [headers.map(escapeCsv).join(',')]
  for (const row of rows) {
    lines.push(
      [
        row.document_no,
        row.invoice_no,
        row.supplier_name,
        row.document_date,
        row.cost_type,
        row.amount,
        row.status,
        row.description,
      ]
        .map(escapeCsv)
        .join(',')
    )
  }
  return `\uFEFF${lines.join('\n')}`
}

/** Minimal printable HTML used for PDF export via browser print / blob. */
export function buildExpenseDocumentHtml(
  doc: AccountingDocument,
  locale: 'fa' | 'en' = 'fa'
): string {
  const isFa = locale === 'fa'
  const dir = isFa ? 'rtl' : 'ltr'
  const title = isFa ? 'سند هزینه' : 'Expense Document'
  const items = doc.expense_items ?? []

  return `<!DOCTYPE html>
<html lang="${isFa ? 'fa' : 'en'}" dir="${dir}">
<head>
  <meta charset="utf-8" />
  <title>${title} ${doc.document_no ?? ''}</title>
  <style>
    body { font-family: Tahoma, Arial, sans-serif; padding: 32px; color: #111; }
    h1 { font-size: 20px; margin: 0 0 8px; }
    .meta { font-size: 13px; color: #444; margin-bottom: 24px; }
    .meta div { margin: 4px 0; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th, td { border: 1px solid #ccc; padding: 8px; text-align: ${isFa ? 'right' : 'left'}; }
    th { background: #f5f5f5; }
    .locked { color: #b45309; font-weight: 600; }
    .footer { margin-top: 28px; font-size: 11px; color: #666; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">
    <div><strong>${isFa ? 'شماره سند' : 'Document No'}:</strong> ${doc.document_no ?? '—'}</div>
    <div><strong>${isFa ? 'شماره فاکتور' : 'Invoice No'}:</strong> ${doc.invoice_no ?? '—'}</div>
    <div><strong>${isFa ? 'تأمین‌کننده' : 'Supplier'}:</strong> ${doc.supplier_name ?? '—'}</div>
    <div><strong>${isFa ? 'تاریخ' : 'Date'}:</strong> ${doc.document_date}</div>
    <div><strong>${isFa ? 'وضعیت' : 'Status'}:</strong> ${doc.status}${
      doc.status === 'finalized' || doc.status === 'submitted'
        ? ` <span class="locked">🔒 ${isFa ? 'قفل‌شده' : 'Locked'}</span>`
        : ''
    }</div>
    <div><strong>${isFa ? 'مبلغ' : 'Amount'}:</strong> ${formatRial(doc.amount, isFa ? 'fa' : 'en')}</div>
    <div><strong>${isFa ? 'شرح' : 'Description'}:</strong> ${doc.description || '—'}</div>
    ${
      doc.correction_of_document_id
        ? `<div><strong>${isFa ? 'اصلاح سند' : 'Correction of'}:</strong> ${doc.correction_of_document_id}</div>`
        : ''
    }
    ${
      doc.reversal_of_document_id
        ? `<div><strong>${isFa ? 'برگشت سند' : 'Reversal of'}:</strong> ${doc.reversal_of_document_id}</div>`
        : ''
    }
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>${isFa ? 'شرح' : 'Description'}</th>
        <th>${isFa ? 'تعداد' : 'Qty'}</th>
        <th>${isFa ? 'قیمت واحد' : 'Unit Price'}</th>
        <th>${isFa ? 'مبلغ' : 'Amount'}</th>
      </tr>
    </thead>
    <tbody>
      ${
        items.length === 0
          ? `<tr><td colspan="5">${isFa ? 'بدون ردیف' : 'No line items'}</td></tr>`
          : items
              .map(
                (item) => `<tr>
          <td>${item.line_no}</td>
          <td>${item.description || '—'}</td>
          <td>${item.quantity}</td>
          <td>${item.unit_price}</td>
          <td>${item.amount}</td>
        </tr>`
              )
              .join('')
      }
    </tbody>
  </table>
  <div class="footer">${isFa ? 'تولیدشده توسط SitePilot — سند حسابداری' : 'Generated by SitePilot — accounting document'}</div>
</body>
</html>`
}

export function downloadTextFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function openPrintableHtml(html: string) {
  const w = window.open('', '_blank')
  if (!w) return
  w.document.write(html)
  w.document.close()
  w.focus()
  setTimeout(() => {
    w.print()
  }, 250)
}

/** Parse simple CSV (comma-separated, supports quoted fields). */
export function parseCsvText(text: string): string[][] {
  const normalized = text.replace(/^\uFEFF/, '')
  const rows: string[][] = []
  let current: string[] = []
  let cell = ''
  let inQuotes = false

  for (let i = 0; i < normalized.length; i++) {
    const ch = normalized[i]
    if (inQuotes) {
      if (ch === '"') {
        if (normalized[i + 1] === '"') {
          cell += '"'
          i++
        } else {
          inQuotes = false
        }
      } else {
        cell += ch
      }
      continue
    }
    if (ch === '"') {
      inQuotes = true
      continue
    }
    if (ch === ',') {
      current.push(cell.trim())
      cell = ''
      continue
    }
    if (ch === '\n') {
      current.push(cell.trim())
      cell = ''
      if (current.some((c) => c.length > 0)) rows.push(current)
      current = []
      continue
    }
    if (ch === '\r') continue
    cell += ch
  }
  current.push(cell.trim())
  if (current.some((c) => c.length > 0)) rows.push(current)
  return rows
}
