-- Seed UI block catalog (auto-generated from lib/dashboard/ui-block-catalog.ts)
-- Run after 32-ui-block-catalog.sql
-- Regenerate: node scripts/generate-ui-blocks-sql.mjs

INSERT INTO public.dashboard_ui_blocks (
  code, key, kind, dashboard, layer, title_fa, title_en, description_fa, legacy_widget_key, sort_order, default_visible
)
VALUES
  ('GEN-WGT-01', 'overview.stats', 'widget', 'general', 'general', 'آمار کلی', 'Overview Stats', 'خلاصه آماری پروژه', 'overview.stats', 10, true),
  ('GEN-WGT-02', 'progress.overview', 'widget', 'general', 'general', 'پیشرفت پروژه', 'Progress Overview', 'برنامه در مقابل واقعی', 'progress.overview', 20, true),
  ('GEN-WGT-03', 'inventory.stock', 'widget', 'general', 'general', 'موجودی انبار', 'Inventory', 'سطح موجودی مواد', 'inventory.stock', 30, true),
  ('GEN-WGT-04', 'reports.recent', 'widget', 'general', 'general', 'گزارش‌های اخیر', 'Recent Reports', 'آخرین گزارش‌های ثبت‌شده', 'reports.recent', 40, true),
  ('GEN-WGT-05', 'reports.daily', 'widget', 'general', 'general', 'گزارش روزانه', 'Daily Report', 'ثبت گزارش روزانه', 'reports.daily', 50, true),
  ('GEN-WGT-06', 'security.alerts', 'widget', 'general', 'general', 'هشدار امنیت', 'Security Alerts', 'اعلان‌های امنیتی', 'security.alerts', 60, false),
  ('GEN-WGT-07', 'security.entry_exit', 'widget', 'general', 'general', 'ورود و خروج', 'Entry/Exit', 'لاگ گیت', 'security.entry_exit', 70, false),
  ('GEN-WGT-08', 'schedule.overview', 'widget', 'general', 'general', 'زمان‌بندی', 'Schedule', 'مایلستون‌های پیش‌رو', 'schedule.overview', 80, true),
  ('GEN-WGT-09', 'safety.overview', 'widget', 'general', 'general', 'ایمنی', 'Safety', 'خلاصه HSE', 'safety.overview', 90, true),
  ('GEN-WGT-10', 'financial.overview', 'widget', 'general', 'general', 'مالی', 'Financial', 'خلاصه هزینه و قرارداد', 'financial.overview', 100, false),
  ('PM-PNL-01', 'pm.panel.executive_summary', 'panel', 'project-manager', 'executive', 'خلاصه مدیریتی', 'Executive Summary', 'وضعیت کلی، فاز، جمع‌بندی روز', NULL, 110, true),
  ('PM-KPI-01', 'pm.kpi.wsi', 'kpi', 'project-manager', 'executive', 'شاخص WSI', 'WSI', 'کفایت نیروی کار', NULL, 111, true),
  ('PM-KPI-02', 'pm.kpi.mrs', 'kpi', 'project-manager', 'executive', 'شاخص MRS', 'MRS', 'آمادگی مصالح', NULL, 112, true),
  ('PM-KPI-03', 'pm.kpi.csi', 'kpi', 'project-manager', 'executive', 'شاخص CSI', 'CSI', 'یکپارچگی زمان‌بندی', NULL, 113, true),
  ('PM-PNL-02', 'pm.panel.top_risks', 'panel', 'project-manager', 'executive', '۳ ریسک اصلی', 'Top 3 Risks', 'ریسک‌های اولویت‌دار', NULL, 114, true),
  ('PM-PNL-03', 'pm.panel.immediate_actions', 'panel', 'project-manager', 'executive', '۳ اقدام فوری', 'Immediate Actions', 'اقدامات کوتاه‌مدت', NULL, 115, true),
  ('PM-ACT-01', 'pm.action.what_now', 'action', 'project-manager', 'executive', 'الان باید چه کار کنم؟', 'What Should I Do Now', 'اقدامات اولویت‌دار', NULL, 116, true),
  ('PM-CHT-01', 'pm.chart.wsi_mrs_trend', 'chart', 'project-manager', 'analytical', 'روند WSI و MRS', 'WSI/MRS Trend', 'نمودار خطی با آستانه', NULL, 120, true),
  ('PM-CHT-02', 'pm.chart.zone_progress', 'chart', 'project-manager', 'analytical', 'وضعیت فعالیت‌های موعد', 'Due activity status', 'میله‌ای انجام/مطابق/عقب/شروع‌نشده', NULL, 121, true),
  ('PM-CHT-03', 'pm.chart.readiness_donut', 'chart', 'project-manager', 'analytical', 'آمادگی کلی', 'Readiness Donut', 'نمودار دونات ترکیبی', NULL, 122, true),
  ('PM-PNL-04', 'pm.panel.risk_alerts', 'panel', 'project-manager', 'analytical', 'هشدارهای ریسک', 'Risk Alerts', 'لیست هشدار رنگی', NULL, 123, true),
  ('PM-PNL-05', 'pm.panel.insights', 'panel', 'project-manager', 'analytical', 'بینش عملیاتی', 'Insights', 'تفسیر خودکار شاخص‌ها', NULL, 124, true),
  ('PM-TBL-01', 'pm.table.approval_center', 'table', 'project-manager', 'operational', 'مرکز تأیید', 'Approval Center', 'درخواست‌های معلق PM', NULL, 130, true),
  ('PM-PNL-06', 'pm.panel.critical_alerts', 'panel', 'project-manager', 'operational', 'هشدارهای بحرانی', 'Critical Alerts', 'اعلان‌های زمان‌بندی', NULL, 131, true),
  ('PM-PNL-07', 'pm.panel.activity_feed', 'panel', 'project-manager', 'operational', 'فعالیت اخیر', 'Activity Feed', 'رویدادهای اخیر', NULL, 132, true),
  ('PM-PNL-08', 'pm.panel.departments', 'panel', 'project-manager', 'operational', 'نمای واحدها', 'Departments', 'خلاصه دپارتمان‌ها', NULL, 133, true),
  ('PM-TBL-02', 'pm.table.recent_reports', 'table', 'project-manager', 'operational', 'گزارش‌های اخیر', 'Recent Reports', 'آرشیو کوتاه گزارش روزانه', NULL, 134, true),
  ('SS-KPI-01', 'ss.kpi.today', 'kpi', 'site-supervisor', 'executive', 'KPI امروز', 'Today KPIs', 'فعالیت، بحرانی، آمادگی', NULL, 210, true),
  ('SS-TBL-01', 'ss.table.today_activities', 'table', 'site-supervisor', 'operational', 'فعالیت‌های امروز', 'Today Activities', 'جدول فعالیت و وضعیت', NULL, 220, true),
  ('SS-PNL-01', 'ss.panel.lookahead', 'panel', 'site-supervisor', 'analytical', 'Lookahead', 'Lookahead', 'پیش‌بینی هفته', NULL, 221, true),
  ('SS-PNL-02', 'ss.panel.resources', 'panel', 'site-supervisor', 'operational', 'منابع', 'Resources', 'مصالح و نیرو', NULL, 222, true),
  ('SS-PNL-03', 'ss.panel.issues_alerts', 'panel', 'site-supervisor', 'operational', 'مسائل و هشدار', 'Issues & Alerts', 'مشکلات میدانی', NULL, 223, true),
  ('SS-PNL-04', 'ss.panel.ai_actions', 'panel', 'site-supervisor', 'operational', 'پیش‌نویس AI', 'AI Drafts', 'اقدامات AI در انتظار تأیید', NULL, 224, true),
  ('SS-ACT-01', 'ss.action.quick_report', 'action', 'site-supervisor', 'operational', 'گزارش سریع', 'Quick Report', 'ثبت گزارش روزانه ساختاریافته', NULL, 225, true),
  ('SK-KPI-01', 'sk.kpi.inventory', 'kpi', 'storekeeper', 'executive', 'KPI انبار', 'Inventory KPIs', 'موجودی، کمبود، ورود/خروج', NULL, 310, true),
  ('SK-TBL-01', 'sk.table.stock', 'table', 'storekeeper', 'operational', 'جدول موجودی', 'Stock Table', 'اقلام انبار', NULL, 320, true),
  ('SK-TBL-02', 'sk.table.transactions', 'table', 'storekeeper', 'operational', 'تراکنش‌ها', 'Transactions', 'ورود و خروج', NULL, 321, true),
  ('SK-ACT-01', 'sk.action.invoice_scan', 'action', 'storekeeper', 'operational', 'اسکن فاکتور', 'Invoice Scan', 'آپلود و استخراج AI', NULL, 322, true),
  ('PR-KPI-01', 'pr.kpi.summary', 'kpi', 'procurement', 'executive', 'KPI تدارکات', 'Procurement KPIs', 'در انتظار، RFQ، در راه', NULL, 410, true),
  ('PR-TBL-01', 'pr.table.incoming_requests', 'table', 'procurement', 'operational', 'درخواست‌های ورودی', 'Incoming Requests', 'خرید تأییدشده PM', NULL, 420, true),
  ('PR-ACT-01', 'pr.action.workflow', 'action', 'procurement', 'operational', 'جریان تأمین', 'Procurement Workflow', 'pending→received', NULL, 421, true),
  ('QC-KPI-01', 'qc.kpi.summary', 'kpi', 'qc', 'executive', 'KPI کیفیت', 'QC KPIs', 'نرخ قبولی، NCR، آزمون', NULL, 510, true),
  ('QC-TBL-01', 'qc.table.inspections', 'table', 'qc', 'operational', 'لیست بازرسی', 'Inspection Worklist', 'فعالیت‌های QC', NULL, 520, true),
  ('QC-TBL-02', 'qc.table.ncr', 'table', 'qc', 'operational', 'مدیریت NCR', 'NCR Management', 'گزارش عدم انطباق', NULL, 521, true),
  ('QC-TBL-03', 'qc.table.lab_tests', 'table', 'qc', 'analytical', 'آزمایشگاه', 'Lab Tests', 'نتایج آزمون', NULL, 522, true),
  ('QC-PNL-01', 'qc.panel.quality_alerts', 'panel', 'qc', 'operational', 'هشدار کیفیت', 'Quality Alerts', 'تولید پیش‌نویس NCR', NULL, 523, true),
  ('HSE-KPI-01', 'hse.kpi.summary', 'kpi', 'hse', 'executive', 'KPI ایمنی', 'HSE KPIs', 'روز بدون حادثه، مخاطره', NULL, 610, true),
  ('HSE-TBL-01', 'hse.table.hazards', 'table', 'hse', 'operational', 'ثبت مخاطره', 'Hazard Log', 'planned', NULL, 620, true),
  ('HSE-TBL-02', 'hse.table.incidents', 'table', 'hse', 'operational', 'حوادث', 'Incidents', 'planned', NULL, 621, true),
  ('SEC-KPI-01', 'sec.kpi.presence', 'kpi', 'security', 'executive', 'خلاصه حضور', 'Presence KPIs', 'داخل، بیرون، غایب، تردد', NULL, 710, true),
  ('SEC-ACT-01', 'sec.action.gate_log', 'action', 'security', 'operational', 'ثبت تردد گیت', 'Gate Transit Log', 'شناسایی و ثبت ورود/خروج', NULL, 720, true),
  ('SEC-PNL-02', 'sec.panel.live_lists', 'panel', 'security', 'operational', 'لیست‌های زنده', 'Live Presence Lists', 'داخل / بیرون / غایب', NULL, 730, true),
  ('SEC-TBL-01', 'sec.table.transits', 'table', 'security', 'operational', 'جدول ترددها', 'Transit Log', 'همه رویدادهای شناسایی امروز', NULL, 740, true),
  ('SEC-PNL-01', 'sec.panel.placeholder', 'panel', 'security', 'general', 'داشبورد امنیت', 'Security Dashboard', 'legacy placeholder', NULL, 799, false),
  ('ACC-KPI-01', 'acc.kpi.total_ac', 'kpi', 'accountant', 'executive', 'جمع هزینه واقعی (AC)', 'Total AC', 'مجموع actual cost از financial_costs', NULL, 810, true),
  ('ACC-KPI-02', 'acc.kpi.total_invoiced', 'kpi', 'accountant', 'executive', 'جمع صورت‌وضعیت صادره', 'Total Invoiced', 'مجموع amount صورت‌وضعیت‌ها', NULL, 811, true),
  ('ACC-KPI-03', 'acc.kpi.total_approved', 'kpi', 'accountant', 'executive', 'جمع تأییدشده کارفرما', 'Total Approved', 'مجموع approved_amount', NULL, 812, true),
  ('ACC-KPI-04', 'acc.kpi.total_paid', 'kpi', 'accountant', 'executive', 'جمع پرداخت‌شده', 'Total Paid', 'مجموع paid_amount / cash-in', NULL, 813, true),
  ('ACC-KPI-05', 'acc.kpi.outstanding', 'kpi', 'accountant', 'executive', 'مطالبات معوق', 'Outstanding Receivables', 'total_approved − total_paid', NULL, 814, true),
  ('ACC-KPI-06', 'acc.kpi.cash_gap', 'kpi', 'accountant', 'executive', 'شکاف نقدینگی', 'Cash Gap', 'AC منهای cash-in', NULL, 815, true),
  ('ACC-TBL-01', 'acc.table.costs', 'table', 'accountant', 'operational', 'جدول هزینه‌ها', 'Cost Records', 'financial_costs با فیلتر', NULL, 820, true),
  ('ACC-TBL-02', 'acc.table.invoices', 'table', 'accountant', 'operational', 'جدول صورت‌وضعیت‌ها', 'Invoices Table', 'invoice_no، دوره، amount، status', NULL, 821, true),
  ('ACC-CHT-01', 'acc.chart.invoice_trend', 'chart', 'accountant', 'analytical', 'روند صورت‌وضعیت ماهانه', 'Invoice Trend', 'amount / approved / paid به تفکیک ماه', NULL, 830, true),
  ('ACC-CHT-02', 'acc.chart.fin_vs_phys', 'chart', 'accountant', 'analytical', 'پیشرفت مالی در برابر فیزیکی', 'Financial vs Physical', 'approved_amount در مقابل project_progress_cost', NULL, 831, true),
  ('ACC-PNL-01', 'acc.panel.alerts', 'panel', 'accountant', 'operational', 'هشدارهای مالی', 'Financial Alerts', 'Approved بدون پرداخت، UnderReview طولانی', NULL, 840, true),
  ('ACC-PNL-02', 'acc.panel.engineering_link', 'panel', 'accountant', 'analytical', 'پیشرفت مهندسی', 'Engineering Progress', 'لینک سبک به project_progress_cost', NULL, 841, true),
  ('ACC-ACT-01', 'acc.action.add_cost', 'action', 'accountant', 'operational', 'ثبت هزینه', 'Add Cost', 'فرم افزودن رکورد financial_costs', NULL, 850, true),
  ('ACC-ACT-02', 'acc.action.add_invoice', 'action', 'accountant', 'operational', 'ثبت صورت‌وضعیت', 'Add Invoice', 'فرم ثبت صورت‌وضعیت کارفرما', NULL, 851, true),
  ('ACC-TBL-03', 'acc.table.vendor_bills', 'table', 'accountant', 'operational', 'بدهی‌ها و ارزش انبار', 'Vendor Bills & Stock', 'vendor_bills و ارزش ریالی انبار', NULL, 822, true),
  ('REQ-001', 'req.purchase_request', 'request', 'cross', 'operational', 'درخواست خرید', 'Purchase Request', 'SS → PM → PR', NULL, 801, true),
  ('REQ-002', 'req.subcontractor_instruction', 'request', 'cross', 'operational', 'دستور پیمانکار', 'Subcontractor Instruction', 'SS → PM', NULL, 802, true),
  ('REQ-003', 'req.hse_alert', 'request', 'cross', 'operational', 'هشدار HSE', 'HSE Alert', 'SS → PM', NULL, 803, true),
  ('REQ-004', 'req.qc_action', 'request', 'cross', 'operational', 'اقدام QC', 'QC Action', 'QC → PM', NULL, 804, true),
  ('REQ-005', 'req.daily_report', 'request', 'cross', 'operational', 'گزارش روزانه', 'Daily Report', 'SS → PM approval', NULL, 805, true),
  ('REQ-006', 'req.pm_comment', 'request', 'cross', 'operational', 'یادداشت به PM', 'PM Comment', 'داخلی سرپرست', NULL, 806, false),
  ('REQ-007', 'req.schedule_change', 'request', 'cross', 'operational', 'تغییر زمان‌بندی', 'Schedule Change', 'planned', NULL, 807, false),
  ('REQ-008', 'req.resource_escalation', 'request', 'cross', 'operational', 'تشدید منابع', 'Resource Escalation', 'planned', NULL, 808, false)
ON CONFLICT (code) DO UPDATE SET
  key = EXCLUDED.key,
  kind = EXCLUDED.kind,
  dashboard = EXCLUDED.dashboard,
  layer = EXCLUDED.layer,
  title_fa = EXCLUDED.title_fa,
  title_en = EXCLUDED.title_en,
  description_fa = EXCLUDED.description_fa,
  legacy_widget_key = EXCLUDED.legacy_widget_key,
  sort_order = EXCLUDED.sort_order,
  default_visible = EXCLUDED.default_visible,
  is_active = true;
